title: "TENSOR Framework"
markdown: kramdown
sass:
  style: compressed

defaults:
  - scope:
      path: "pages"
    values:
      permalink: "/:basename/"

collections:
  graphs:
    output: true
    permalink: /graphs/:path/
  schemas:
    output: true
    permalink: /schemas/:path/

# site/_config.yml
navigation:
  - title: "About"
    url: "/about/"
  - title: "Docs"
    url: "/docs/"
  - title: "Schemas"
    url: "/schemas/"
  - title: "Graphs"
    url: "/graphs/"
  - title: "Extensions"
    url: "/extensions/"
  - title: "Graph Studio"
    url: "/studio/"
  - title: "GitHub"
    url: "https://github.com/tensor-standards-consortium/tensor-framework"
